name: Rabee
packages:
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI
    from: 2.2.3
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: 5.6.4
configs:
  Rabee-DEV: debug
  Rabee: release
configFiles:
  Rabee-DEV: Config/Rabee-DEV.xcconfig
  Rabee: Config/Rabee.xcconfig
settings:
  base:
    # USER DEFINED PROJECT
    BUILD_NUMBER: $(BUILD_NUMBER)
    VERSION_NAME: $(VERSION_NAME)
    CURRENT_PROJECT_VERSION: $(BUILD_NUMBER)
    MARKETING_VERSION: $(VERSION_NAME)
targets:
  Rabee:
    type: application
    platform: iOS
    deploymentTarget: "16.4"
    sources:
      - path: Rabee
        name: Rabee
    settings:
      base:
      # USER DEFINED TARGET
        INFOPLIST_FILE: Rabee/Supporting Files/Info.plist
        GENERATE_INFOPLIST_FILE: NO
      configs:
        Rabee-DEV:
          PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          PRODUCT_NAME: Rabee
          DEVELOPMENT_TEAM: 94XJVN3C32
        Rabee:
          PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
          PRODUCT_NAME: Rabee
          DEVELOPMENT_TEAM: 94XJVN3C32
    dependencies:
      - package: SDWebImageSwiftUI
      - package: Alamofire
schemes:
  Rabee:
    build:
      targets:
        Rabee: all
    run:
      config: Rabee
    profile:
      config: Rabee
    analyze:
      config: Rabee
    archive: Rabee
  Rabee-DEV:
    build:
      targets:
        Rabee: all
    run:
      config: Rabee-DEV
    profile:
      config: Rabee-DEV
    analyze:
      config: Rabee-DEV
    archive:
      config: Rabee-DEV
